CREATE USER ${DAGSTER_POSTGRES_USER} WITH PASSWORD '${DAGSTER_POSTGRES_PASSWORD}';
CREATE DATABASE ${DAGSTER_POSTGRES_DB};
GRANT ALL PRIVILEGES ON DATABASE ${DAGSTER_POSTGRES_DB} TO ${DAGSTER_POSTGRES_USER};

-- Create analytics schema for dbt
\c ${POSTGRES_DB}
CREATE SCHEMA IF NOT EXISTS ${DBT_TARGET_SCHEMA};